#!/bin/sh
archive=$1
database=$2
script=/tmp/rdb-`date +%Y%m%d%H%M%S%N`.sql
echo "\\\\c postgres" > ${script}
echo "DROP DATABASE $database;" >> ${script}
echo "CREATE DATABASE $database;" >> ${script}
echo "\\\\c $database" >> ${script}
echo "\\\\i $archive" >> ${script}
echo "\\\\qecho 'Database reloaded!'" >> ${script}
psql -f $script postgres
rm $script
